### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray-bram-patch#3]
This repository should have a LICENSE file.

Our preferred license is [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) or [ISC](https://opensource.org/licenses/ISC).

Please make sure that GitHub is correctly detecting the license and displaying it at
![image](https://user-images.githubusercontent.com/21212/75912933-d71c6b00-5e06-11ea-880f-830dd73f4b83.png)

**Comment by nelsobe** [comment]
Copied what prjxray is using.
