### ISSUE TITLE
Please make sure all commits have signoff lines

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray-bram-patch#4]
We require all commits to SymbiFlow projects to have the [Developer Certificate of Origin](https://developercertificate.org/) explicitly acknowledged. This is done through adding a `Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>` line to the bottom of each commit message.

You can do this easily with git via the `git commit --amend --signoff` and `git rebase --signoff` commands.

There is more information about this at;
 - https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for
 - https://github.com/probot/dco
 - https://cert-manager.io/docs/contributing/sign-off/

**Comment by nelsobe** [comment]
Was able to do all but 14b7333f4789c5d9bef95390ccd9dd1b58371583.  Not sure why I couldn't do that one.
